.SILENT:

VMFILES = nmwiz.tcl pkgIndex.tcl

VMVERSION = 1.1
DIR = $(PLUGINDIR)/noarch/tcl/nmwiz$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying nmwiz $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
