#!/usr/bin/env python

from prody.utilities.misctools import impLoadModule
import importlib

path_apps = importlib.util.find_spec("prody.apps").submodule_search_locations[0]
apps = impLoadModule('prody.apps.evol_apps', path_apps + '/evol_apps/', '__init__')

if __name__ == '__main__':
    apps.evol_main()