#!/usr/bin/env python

from prody.utilities.misctools import importImp
imp = importImp()
import importlib
if sys.version_info[0] == 2:
    path_prody = imp.find_module('prody')[1]
else:
    path_prody = importlib.util.find_spec("prody").submodule_search_locations[0]
apps = imp.find_module('apps', [path])
apps = imp.load_module('prody.apps', *apps)

if __name__ == '__main__':
    apps.evol_main()