#!/usr/bin/env python

import imp
import importlib
#path = imp.find_module('prody')[1]
path = importlib.util.find_spec("prody").submodule_search_locations[0]
apps = imp.find_module('apps', [path])
apps = imp.load_module('prody.apps', *apps)

if __name__ == '__main__':
    apps.evol_main()