#!/usr/bin/env python

try:
    import imp
except ImportError:
    import importlib as imp
    
path = imp.find_module('prody')[1]
apps = imp.find_module('apps', [path])
apps = imp.load_module('prody.apps', *apps)

if __name__ == '__main__':
    apps.prody_main()