#!/usr/bin/env python

import imp
path = imp.find_module('prody')[1]
apps = imp.find_module('apps', [path])
apps = imp.load_module('prody.apps', *apps)

if __name__ == '__main__':
    apps.prody_main()